In [1]:
import numpy as np

### Generating the random number sequence

In [2]:
np.random.random()

0.6309711047676386

In [3]:
np.random.seed(10)
np.random.random()

0.771320643266746

In [4]:
np.random.seed()
np.random.random()

0.5265875140382047

In [5]:
np.random.random(4) # Ranges from 0 -1

array([0.0093966 , 0.51876079, 0.01672195, 0.94827806])

In [6]:
x = np.random.random(10)

In [7]:
y = np.append(x, np.random.random(5))

In [8]:
y

array([0.36464872, 0.28618093, 0.20345988, 0.96642694, 0.10342423,
       0.28314785, 0.15409606, 0.835559  , 0.47302671, 0.49992987,
       0.26980722, 0.87934621, 0.88278959, 0.8785736 , 0.62310896])

In [9]:
z = np.zeros(10)
z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [10]:
z = np.zeros(10, dtype = int)
z

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [11]:
z = np.ones(10, dtype = int)
z

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [12]:
z = np.zeros((5,5), dtype = int)
z

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [13]:
garbage_values = np.empty(10, dtype = int)
garbage_values

array([        23135225482,                   0,                   0,
                         0,     136889197658112, 7149237051692953698,
       3977854073115457069, 3271361795107677794, 3630574635461129527,
           136890009412198])

In [14]:
a_range = np.arange(5)

In [15]:
a_range_2 = np.arange(21, 77)
a_range_2

array([21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37,
       38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54,
       55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71,
       72, 73, 74, 75, 76])

In [16]:
a_range_3 = np.arange(21, 80, 3)
a_range_3

array([21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51, 54, 57, 60, 63, 66, 69,
       72, 75, 78])

In [17]:
a_range_reshape = np.arange(21, 80, 3).reshape(4, 5)
a_range_reshape

array([[21, 24, 27, 30, 33],
       [36, 39, 42, 45, 48],
       [51, 54, 57, 60, 63],
       [66, 69, 72, 75, 78]])

In [18]:
# arange : starting point, ending point , steps
# ---> Auto finds the number of values to be generated . Ending point is exclusive

# linspace : starting point, ending point , number of values
# ---> Finds out the step required. Ending point is inclusive

In [19]:
np.linspace(1, 7, num = 5, dtype = int)

array([1, 2, 4, 5, 7])

In [20]:
np.linspace(1, 7, num = 5, endpoint = False, dtype = int)

array([1, 2, 3, 4, 5])

In [21]:
np.linspace(1, 7, num = 5, endpoint = False , dtype = int, retstep = True)

(array([1, 2, 3, 4, 5]), 1.2)

### Find the Square root , Power, square

In [22]:
s = 10
sroot = np.sqrt(s)
sroot

3.1622776601683795

In [23]:
p = np.power(3, 2)
p

9

In [24]:
a = np.linspace(1, 10, num = 5, dtype = int)
a

array([ 1,  3,  5,  7, 10])

In [25]:
a.ndim

1

In [26]:
a.shape

(5,)

In [27]:
i = np.identity(5)
i

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [28]:
np.random.random((5, 3, 5))

array([[[0.645862  , 0.252595  , 0.35352787, 0.97640375, 0.25525027],
        [0.01401004, 0.02909787, 0.55625408, 0.36443606, 0.62583298],
        [0.61723643, 0.67675541, 0.21572836, 0.87097883, 0.31227881]],

       [[0.97585189, 0.32528561, 0.9978042 , 0.41943846, 0.54163482],
        [0.60521396, 0.36324439, 0.64205277, 0.28170814, 0.74940131],
        [0.16576572, 0.77987241, 0.31296088, 0.53584751, 0.44866027]],

       [[0.26540617, 0.51847057, 0.46379276, 0.07000203, 0.06449991],
        [0.71361419, 0.60270989, 0.07735822, 0.44522312, 0.8763869 ],
        [0.8130564 , 0.40959516, 0.4877316 , 0.31680701, 0.4773431 ]],

       [[0.51988   , 0.10153152, 0.89153518, 0.88103887, 0.44141551],
        [0.89093369, 0.02350025, 0.63892856, 0.32502347, 0.21531364],
        [0.75310703, 0.84738827, 0.73418069, 0.52287555, 0.176896  ]],

       [[0.1135675 , 0.77901617, 0.7225275 , 0.53917343, 0.74810468],
        [0.2834601 , 0.59414608, 0.74004087, 0.64406098, 0.96259754],
        [0.4

### Slicing of Array

In [29]:
slice = np.arange(30).reshape(3, 2, 5)

In [30]:
slice.shape

(3, 2, 5)

In [31]:
slice[1:]

array([[[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

In [32]:
slice[1:, 1:]

array([[[15, 16, 17, 18, 19]],

       [[25, 26, 27, 28, 29]]])

In [33]:
slice[1:, 1:, 0::2]

array([[[15, 17, 19]],

       [[25, 27, 29]]])

In [34]:
slice%2 ==0

array([[[ True, False,  True, False,  True],
        [False,  True, False,  True, False]],

       [[ True, False,  True, False,  True],
        [False,  True, False,  True, False]],

       [[ True, False,  True, False,  True],
        [False,  True, False,  True, False]]])

In [35]:
slice[slice % 2 == 0 ].reshape(3, 1, 5)

array([[[ 0,  2,  4,  6,  8]],

       [[10, 12, 14, 16, 18]],

       [[20, 22, 24, 26, 28]]])

###Aggregations with MultiDimensional data

In [36]:
slice

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

In [37]:
np.sum(slice)

435

In [38]:
np.sum(slice, axis = 0)

array([[30, 33, 36, 39, 42],
       [45, 48, 51, 54, 57]])

In [39]:
np.sum(slice, axis = 1)

array([[ 5,  7,  9, 11, 13],
       [25, 27, 29, 31, 33],
       [45, 47, 49, 51, 53]])

In [40]:
# Converting the multi dimensional array into single dimension
slice.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [41]:
slice.reshape(1, slice.shape[0] * slice.shape[1] * slice.shape[2])

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [42]:
np.random.choice(slice.flatten(), 5)

array([12, 25, 22,  8, 27])

In [43]:
np.random.choice(['x', 'y', 'z'], 1000)

array(['y', 'y', 'x', 'y', 'y', 'x', 'z', 'y', 'z', 'y', 'x', 'z', 'x',
       'z', 'x', 'x', 'x', 'z', 'x', 'y', 'y', 'x', 'y', 'z', 'y', 'z',
       'y', 'x', 'y', 'z', 'z', 'y', 'x', 'x', 'y', 'x', 'z', 'z', 'y',
       'x', 'z', 'z', 'x', 'x', 'x', 'z', 'z', 'y', 'x', 'z', 'y', 'y',
       'z', 'y', 'y', 'z', 'x', 'z', 'z', 'y', 'y', 'z', 'z', 'z', 'z',
       'y', 'z', 'y', 'z', 'z', 'z', 'z', 'y', 'y', 'z', 'x', 'x', 'y',
       'z', 'x', 'y', 'y', 'z', 'x', 'z', 'x', 'z', 'x', 'x', 'y', 'z',
       'z', 'y', 'x', 'z', 'x', 'z', 'x', 'z', 'x', 'x', 'z', 'y', 'y',
       'z', 'x', 'x', 'x', 'x', 'x', 'x', 'x', 'z', 'z', 'x', 'z', 'x',
       'y', 'y', 'z', 'y', 'y', 'y', 'x', 'z', 'y', 'x', 'y', 'z', 'x',
       'z', 'y', 'y', 'y', 'x', 'x', 'z', 'y', 'x', 'y', 'x', 'y', 'y',
       'x', 'z', 'x', 'x', 'y', 'z', 'x', 'x', 'y', 'z', 'x', 'x', 'z',
       'x', 'z', 'z', 'y', 'x', 'y', 'z', 'z', 'y', 'x', 'x', 'z', 'z',
       'x', 'z', 'y', 'z', 'z', 'z', 'x', 'z', 'z', 'y', 'z', 'x

In [44]:
np.unique(np.random.choice(['x', 'y', 'z'], 1000), return_counts = True)

(array(['x', 'y', 'z'], dtype='<U1'), array([332, 335, 333]))

In [45]:
np.random.choice(['x', 'y', 'z'], 1000 , p = [.7, .2, .1])

array(['x', 'y', 'y', 'y', 'x', 'x', 'x', 'x', 'x', 'x', 'x', 'y', 'x',
       'x', 'x', 'x', 'x', 'z', 'x', 'y', 'x', 'z', 'x', 'x', 'z', 'x',
       'z', 'x', 'x', 'x', 'x', 'x', 'x', 'x', 'y', 'x', 'z', 'y', 'x',
       'x', 'x', 'y', 'y', 'x', 'x', 'z', 'x', 'y', 'x', 'y', 'x', 'y',
       'z', 'x', 'z', 'x', 'x', 'x', 'z', 'x', 'x', 'x', 'x', 'z', 'x',
       'x', 'z', 'x', 'x', 'z', 'x', 'y', 'x', 'x', 'x', 'x', 'x', 'x',
       'x', 'x', 'x', 'x', 'x', 'x', 'x', 'x', 'x', 'x', 'y', 'x', 'x',
       'x', 'z', 'z', 'x', 'x', 'z', 'x', 'x', 'y', 'x', 'z', 'y', 'x',
       'z', 'x', 'x', 'x', 'x', 'y', 'y', 'y', 'x', 'y', 'x', 'z', 'z',
       'x', 'x', 'x', 'x', 'x', 'x', 'x', 'x', 'x', 'x', 'z', 'y', 'x',
       'x', 'z', 'y', 'x', 'x', 'x', 'x', 'x', 'x', 'x', 'x', 'x', 'x',
       'x', 'x', 'x', 'x', 'x', 'y', 'y', 'y', 'z', 'x', 'x', 'y', 'x',
       'x', 'z', 'x', 'x', 'x', 'x', 'z', 'x', 'x', 'y', 'y', 'x', 'x',
       'x', 'y', 'x', 'x', 'x', 'x', 'y', 'x', 'x', 'x', 'x', 'x

In [46]:
np.unique(np.random.choice(['x', 'y', 'z'], 1000 , p = [.7, .2, .1]), return_counts = True)

(array(['x', 'y', 'z'], dtype='<U1'), array([683, 219,  98]))

In [47]:
np.random.randint(
    low = 25,
    high = 990,
    size = (5, 5)
)

array([[326, 761, 466, 844, 800],
       [900, 497, 849, 435, 898],
       [530, 598, 331, 447, 463],
       [976, 230, 216, 238, 175],
       [294, 911, 431, 383, 268]])

### File Handling

In [48]:
file_obj_w = open('demo_text_1', 'w')
print(file_obj_w.mode)

w


In [49]:
file_obj_w = open('demo_text_1', 'w')

print("Mode : ", file_obj_w.mode)
print("Is Readable : ", file_obj_w.readable())
print("Is Writable : ", file_obj_w.writable())

Mode :  w
Is Readable :  False
Is Writable :  True


In [50]:
file_obj_w.write("Hello World, My name is Althaf ! This is a new text")
file_obj_w.writelines(" \n This is the appended text using WriteLines function !!!!")
file_obj_w.writelines(" \n This is the appended text using WriteLines function !!!!")

In [51]:
file_obj_w.close()

In [52]:
file_obj_r = open('demo_text_1', 'r')
print(file_obj_r)

<_io.TextIOWrapper name='demo_text_1' mode='r' encoding='UTF-8'>


In [53]:
for char in file_obj_r:
  print(char)

Hello World, My name is Althaf ! This is a new text 

 This is the appended text using WriteLines function !!!! 

 This is the appended text using WriteLines function !!!!


In [54]:
file_obj_w = open('demo_text_1', 'w')
file_obj_w.writelines(" \n =============================================== !!!!")
file_obj_w.close()

In [55]:
file_obj_r = open('demo_text_1', 'r')
for char in file_obj_r:
  print(char)

 

 =============================================== !!!!


In [56]:
my_data = ['This is Sentence_1 ======= = === = == ', 'This is Sentence_2 ======= = === = == ', 'This is Sentence_3 ======= = === = == ']

In [57]:
file_obj_w = open('demo_for_loop.txt', 'w')

for data in my_data:
  file_obj_w.write(data)

file_obj_w.close()

In [58]:
file_obj_r = open('demo_for_loop.txt', 'r')
for data in file_obj_r:
  print(data, "\n")

This is Sentence_1 ======= = === = == This is Sentence_2 ======= = === = == This is Sentence_3 ======= = === = ==  



In [59]:
### Apending the data

my_data = ['\n -----  USing the Append functionality',
           'This is Sentence_1 ======= = === = == ',
           'This is Sentence_2 ======= = === = == ',
           'This is Sentence_3 ======= = === = == ']

file_obj_w = open('demo_for_loop.txt', 'a')

for data in my_data:
  file_obj_w.writelines(data)

file_obj_w.close()

In [60]:
### Reading the data

file_obj_r = open('demo_for_loop.txt', 'r')

print(file_obj_r.readline())


This is Sentence_1 ======= = === = == This is Sentence_2 ======= = === = == This is Sentence_3 ======= = === = == 



### Reading a csv file

In [61]:
import pandas as pd

data_csv = pd.read_csv('/content/sample_data/mnist_train_small.csv')

In [62]:
data_csv.head(5)

6  0  0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  ...  0.581  0.582  0.583  \
0  5  0    0    0    0    0    0    0    0    0  ...      0      0      0   
1  7  0    0    0    0    0    0    0    0    0  ...      0      0      0   
2  9  0    0    0    0    0    0    0    0    0  ...      0      0      0   
3  5  0    0    0    0    0    0    0    0    0  ...      0      0      0   
4  2  0    0    0    0    0    0    0    0    0  ...      0      0      0   

   0.584  0.585  0.586  0.587  0.588  0.589  0.590  
0      0      0      0      0      0      0      0  
1      0      0      0      0      0      0      0  
2      0      0      0      0      0      0      0  
3      0      0      0      0      0      0      0  
4      0      0      0      0      0      0      0  

[5 rows x 785 columns]

### Pandas

In [63]:
import pandas as pd
import numpy as np

In [64]:
id = np.random.randint(20, 2000, 20)
id

array([ 855,  313,  608, 1746, 1120, 1044,  958,  618,  319,  247, 1097,
        269,  704,  606,  516,   96,  433, 1736, 1709, 1616])

In [65]:
age = np.random.randint(15, 65, [20,])
age

array([23, 34, 54, 61, 47, 44, 64, 28, 53, 51, 61, 27, 17, 33, 28, 48, 58,
       58, 48, 33])

In [66]:
city = np.random.choice(['NY', 'DL', 'PR', 'MUM'], 20)
city

array(['DL', 'DL', 'MUM', 'MUM', 'PR', 'PR', 'NY', 'NY', 'PR', 'NY', 'DL',
       'DL', 'PR', 'PR', 'NY', 'NY', 'PR', 'MUM', 'MUM', 'MUM'],
      dtype='<U3')

In [67]:
approval = np.random.choice([0,1], 20)
approval

array([1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1])

In [68]:
dataframe_list = list(zip(id, age, city, approval))

In [69]:
dataframe_list

[(855, 23, 'DL', 1),
 (313, 34, 'DL', 1),
 (608, 54, 'MUM', 0),
 (1746, 61, 'MUM', 1),
 (1120, 47, 'PR', 0),
 (1044, 44, 'PR', 0),
 (958, 64, 'NY', 1),
 (618, 28, 'NY', 1),
 (319, 53, 'PR', 1),
 (247, 51, 'NY', 0),
 (1097, 61, 'DL', 1),
 (269, 27, 'DL', 0),
 (704, 17, 'PR', 0),
 (606, 33, 'PR', 0),
 (516, 28, 'NY', 0),
 (96, 48, 'NY', 0),
 (433, 58, 'PR', 0),
 (1736, 58, 'MUM', 0),
 (1709, 48, 'MUM', 1),
 (1616, 33, 'MUM', 1)]

In [70]:
df = pd.DataFrame(data = dataframe_list, columns = ['id', 'age', 'city', 'approval'])

In [71]:
df.head(5)

id  age city  approval
0   855   23   DL         1
1   313   34   DL         1
2   608   54  MUM         0
3  1746   61  MUM         1
4  1120   47   PR         0

In [72]:
df.tail(5)

id  age city  approval
15    96   48   NY         0
16   433   58   PR         0
17  1736   58  MUM         0
18  1709   48  MUM         1
19  1616   33  MUM         1

In [73]:
df[df.age > 50]

id  age city  approval
2    608   54  MUM         0
3   1746   61  MUM         1
6    958   64   NY         1
8    319   53   PR         1
9    247   51   NY         0
10  1097   61   DL         1
16   433   58   PR         0
17  1736   58  MUM         0

In [75]:
bank_data = pd.read_csv('/content/sample_data/bank_data.csv')
bank_data.head(5)

age           job  marital  education default  balance housing loan  \
0   58    management  married   tertiary      no     2143     yes   no   
1   44    technician   single  secondary      no       29     yes   no   
2   33  entrepreneur  married  secondary      no        2     yes  yes   
3   47   blue-collar  married    unknown      no     1506     yes   no   
4   33       unknown   single    unknown      no        1      no   no   

   contact  day month  duration  campaign  pdays  previous poutcome   y  
0  unknown    5   may       261         1     -1         0  unknown  no  
1  unknown    5   may       151         1     -1         0  unknown  no  
2  unknown    5   may        76         1     -1         0  unknown  no  
3  unknown    5   may        92         1     -1         0  unknown  no  
4  unknown    5   may       198         1     -1         0  unknown  no

In [76]:
bank_data.columns

Index(['age', 'job', 'marital', 'education', 'default', 'balance', 'housing',
       'loan', 'contact', 'day', 'month', 'duration', 'campaign', 'pdays',
       'previous', 'poutcome', 'y'],
      dtype='object')

In [77]:
bank_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45211 entries, 0 to 45210
Data columns (total 17 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   age        45211 non-null  int64 
 1   job        45211 non-null  object
 2   marital    45211 non-null  object
 3   education  45211 non-null  object
 4   default    45211 non-null  object
 5   balance    45211 non-null  int64 
 6   housing    45211 non-null  object
 7   loan       45211 non-null  object
 8   contact    45211 non-null  object
 9   day        45211 non-null  int64 
 10  month      45211 non-null  object
 11  duration   45211 non-null  int64 
 12  campaign   45211 non-null  int64 
 13  pdays      45211 non-null  int64 
 14  previous   45211 non-null  int64 
 15  poutcome   45211 non-null  object
 16  y          45211 non-null  object
dtypes: int64(7), object(10)
memory usage: 5.9+ MB


In [78]:
bank_data.describe()

age        balance           day      duration      campaign  \
count  45211.000000   45211.000000  45211.000000  45211.000000  45211.000000   
mean      40.936210    1362.272058     15.806419    258.163080      2.763841   
std       10.618762    3044.765829      8.322476    257.527812      3.098021   
min       18.000000   -8019.000000      1.000000      0.000000      1.000000   
25%       33.000000      72.000000      8.000000    103.000000      1.000000   
50%       39.000000     448.000000     16.000000    180.000000      2.000000   
75%       48.000000    1428.000000     21.000000    319.000000      3.000000   
max       95.000000  102127.000000     31.000000   4918.000000     63.000000   

              pdays      previous  
count  45211.000000  45211.000000  
mean      40.197828      0.580323  
std      100.128746      2.303441  
min       -1.000000      0.000000  
25%       -1.000000      0.000000  
50%       -1.000000      0.000000  
75%       -1.000000      0.000000  
max      871.000000    275.000000

In [79]:
bank_data.dtypes

age           int64
job          object
marital      object
education    object
default      object
balance       int64
housing      object
loan         object
contact      object
day           int64
month        object
duration      int64
campaign      int64
pdays         int64
previous      int64
poutcome     object
y            object
dtype: object

In [80]:
bank_data.shape

(45211, 17)

In [81]:
bank_data.iloc[1, 2]

'single'

In [82]:
bank_data.iloc[1:5, 2:4]

marital  education
1   single  secondary
2  married  secondary
3  married    unknown
4   single    unknown

In [83]:
bank_data.head(5)

age           job  marital  education default  balance housing loan  \
0   58    management  married   tertiary      no     2143     yes   no   
1   44    technician   single  secondary      no       29     yes   no   
2   33  entrepreneur  married  secondary      no        2     yes  yes   
3   47   blue-collar  married    unknown      no     1506     yes   no   
4   33       unknown   single    unknown      no        1      no   no   

   contact  day month  duration  campaign  pdays  previous poutcome   y  
0  unknown    5   may       261         1     -1         0  unknown  no  
1  unknown    5   may       151         1     -1         0  unknown  no  
2  unknown    5   may        76         1     -1         0  unknown  no  
3  unknown    5   may        92         1     -1         0  unknown  no  
4  unknown    5   may       198         1     -1         0  unknown  no

In [84]:
bank_data[['age', 'job', 'education', 'housing', 'loan']]

age           job  education housing loan
0       58    management   tertiary     yes   no
1       44    technician  secondary     yes   no
2       33  entrepreneur  secondary     yes  yes
3       47   blue-collar    unknown     yes   no
4       33       unknown    unknown      no   no
...    ...           ...        ...     ...  ...
45206   51    technician   tertiary      no   no
45207   71       retired    primary      no   no
45208   72       retired  secondary      no   no
45209   57   blue-collar  secondary      no   no
45210   37  entrepreneur  secondary      no   no

[45211 rows x 5 columns]

In [85]:
bank_data.loc[
    (bank_data['age'] == 30) & (bank_data['loan'] == 'yes'),
    ['age', 'education', 'job']
]

age  education            job
91      30  secondary     technician
529     30  secondary         admin.
798     30  secondary    blue-collar
1047    30   tertiary     technician
1214    30   tertiary     management
...    ...        ...            ...
41503   30  secondary    blue-collar
42320   30   tertiary         admin.
43978   30  secondary     technician
44222   30  secondary  self-employed
44344   30   tertiary         admin.

[288 rows x 3 columns]

In [86]:
bank_data.loc[
    ~(bank_data['age'] == 30) & (bank_data['loan'] == 'yes'),
    ['age', 'education', 'job']
]

age  education           job
2       33  secondary  entrepreneur
6       28   tertiary    management
20      28  secondary   blue-collar
22      32    primary   blue-collar
24      40    primary       retired
...    ...        ...           ...
45122   40   tertiary  entrepreneur
45151   47   tertiary    management
45153   64   tertiary       retired
45194   59   tertiary    management
45205   25  secondary    technician

[6956 rows x 3 columns]

In [87]:
bank_data.drop(['age', 'job'], axis = 1)

marital  education default  balance housing loan    contact  day  \
0       married   tertiary      no     2143     yes   no    unknown    5   
1        single  secondary      no       29     yes   no    unknown    5   
2       married  secondary      no        2     yes  yes    unknown    5   
3       married    unknown      no     1506     yes   no    unknown    5   
4        single    unknown      no        1      no   no    unknown    5   
...         ...        ...     ...      ...     ...  ...        ...  ...   
45206   married   tertiary      no      825      no   no   cellular   17   
45207  divorced    primary      no     1729      no   no   cellular   17   
45208   married  secondary      no     5715      no   no   cellular   17   
45209   married  secondary      no      668      no   no  telephone   17   
45210   married  secondary      no     2971      no   no   cellular   17   

      month  duration  campaign  pdays  previous poutcome    y  
0       may       261         1     -1         0  unknown   no  
1       may       151         1     -1         0  unknown   no  
2       may        76         1     -1         0  unknown   no  
3       may        92         1     -1         0  unknown   no  
4       may       198         1     -1         0  unknown   no  
...     ...       ...       ...    ...       ...      ...  ...  
45206   nov       977         3     -1         0  unknown  yes  
45207   nov       456         2     -1         0  unknown  yes  
45208   nov      1127         5    184         3  success  yes  
45209   nov       508         4     -1         0  unknown   no  
45210   nov       361         2    188        11    other   no  

[45211 rows x 15 columns]

### Sorting and Merging dataframes

In [88]:
"""
Sorting data by one or more columns in ascending or descending order
Combining dataframes vertically or horizontally
Merging them using keys, left , right, inner and outer join
"""

'\nSorting data by one or more columns in ascending or descending order\nCombining dataframes vertically or horizontally\nMerging them using keys, left , right, inner and outer join\n'

In [89]:
import pandas as pd
import numpy as np

In [90]:
dataframe = pd.DataFrame(np.random.randint(2, 8, (20, 4)), columns = list('ABCD'))

In [91]:
dataframe.head(5)

A  B  C  D
0  7  6  5  5
1  3  4  3  3
2  5  6  7  5
3  3  2  4  5
4  2  7  7  5

In [92]:
# Sorting based on columns
dataframe.sort_values('A', ascending = True)

A  B  C  D
4   2  7  7  5
9   3  4  7  2
3   3  2  4  5
19  3  4  6  6
1   3  4  3  3
7   4  2  2  4
18  4  7  6  4
14  4  5  7  3
10  5  2  7  2
13  5  7  3  7
15  5  7  3  6
16  5  7  7  2
2   5  6  7  5
5   6  4  6  2
8   6  6  3  3
11  6  6  7  6
12  6  3  6  3
17  6  2  3  6
6   7  6  6  5
0   7  6  5  5

In [93]:
dataframe.sort_values('A', ascending = False)

A  B  C  D
0   7  6  5  5
6   7  6  6  5
11  6  6  7  6
17  6  2  3  6
5   6  4  6  2
8   6  6  3  3
12  6  3  6  3
16  5  7  7  2
15  5  7  3  6
13  5  7  3  7
10  5  2  7  2
2   5  6  7  5
7   4  2  2  4
14  4  5  7  3
18  4  7  6  4
1   3  4  3  3
9   3  4  7  2
3   3  2  4  5
19  3  4  6  6
4   2  7  7  5

In [94]:
# Multiple Columns
dataframe.sort_values(['A', 'B'], ascending = [True, False])

A  B  C  D
4   2  7  7  5
1   3  4  3  3
9   3  4  7  2
19  3  4  6  6
3   3  2  4  5
18  4  7  6  4
14  4  5  7  3
7   4  2  2  4
13  5  7  3  7
15  5  7  3  6
16  5  7  7  2
2   5  6  7  5
10  5  2  7  2
8   6  6  3  3
11  6  6  7  6
5   6  4  6  2
12  6  3  6  3
17  6  2  3  6
0   7  6  5  5
6   7  6  6  5

In [95]:
## Combining multiple dataframes (stacking)

In [96]:
df1 = pd.DataFrame(
    [
        ['a', 1], ['b', 2]
    ], columns = ['letter', 'number']
)

In [97]:
df2 = pd.DataFrame(
    [
        ['c', 3, 'cat'], ['d', 4, 'dog']
    ], columns = ['letter', 'number', 'animal']
)

In [98]:
df1

letter  number
0      a       1
1      b       2

In [99]:
df2

letter  number animal
0      c       3    cat
1      d       4    dog

In [100]:
pd.concat([df1, df2], axis = 0)

letter  number animal
0      a       1    NaN
1      b       2    NaN
0      c       3    cat
1      d       4    dog

In [101]:
pd.concat([df1, df2], axis = 1)

letter  number letter  number animal
0      a       1      c       3    cat
1      b       2      d       4    dog

In [102]:
pd.concat([df1, df2], axis = 0, ignore_index = True)

letter  number animal
0      a       1    NaN
1      b       2    NaN
2      c       3    cat
3      d       4    dog

In [103]:
df3 = pd.DataFrame(
    [
        ['bird', 'polly'], ['monkey', 'george'], ['tiger', 'john']
    ], columns = ['animal', 'name']
)

In [104]:
df3

animal    name
0    bird   polly
1  monkey  george
2   tiger    john

In [105]:
pd.merge(df1, df2, on = ['number'], how = 'outer')

letter_x  number letter_y animal
0        a       1      NaN    NaN
1        b       2      NaN    NaN
2      NaN       3        c    cat
3      NaN       4        d    dog

### Stack Unstack Melt

In [106]:
df3

animal    name
0    bird   polly
1  monkey  george
2   tiger    john

In [107]:
pd.get_dummies(df3.head(), columns = ['animal', 'name'])

animal_bird  animal_monkey  animal_tiger  name_george  name_john  \
0            1              0             0            0          0   
1            0              1             0            1          0   
2            0              0             1            0          1   

   name_polly  
0           1  
1           0  
2           0

### Data Preparation

In [108]:
import numpy as np
import pandas as pd

In [109]:
age = np.random.choice([15, 20, 30, 45, 12, '10', 15, '34', 7, 'missing'], 50)
fico = np.random.choice(['100-150', '150-200', '200-250', '250-300'], 50)
city = np.random.choice(['Mumbai', 'Delhi', 'Chennai', 'Kolkata'], 50)
ID = np.arange(50)
rating = np.random.choice(['Excellent', 'Good', 'Bad', 'Pathetic'], 50)
balance = np.random.choice([10000, 20000, 30000, 40000, np.nan, 50000, 60000], 50)
children = np.random.randint(high = 5, low = 0, size = (50, ))

In [110]:
mydata = pd.DataFrame(
    {
        'ID' : ID,
        'age' : age,
        'fico' : fico,
        'city' : city,
        'rating' : rating,
        'balance' : balance,
        'children' : children
    }
)

In [111]:
mydata.head(10)

ID      age     fico     city     rating  balance  children
0   0  missing  100-150   Mumbai   Pathetic  50000.0         1
1   1        7  200-250  Chennai   Pathetic  30000.0         2
2   2       20  200-250  Chennai   Pathetic      NaN         3
3   3       20  200-250  Kolkata       Good  60000.0         3
4   4       15  100-150  Kolkata   Pathetic  30000.0         3
5   5       20  200-250  Chennai        Bad  60000.0         3
6   6       34  200-250    Delhi        Bad  60000.0         4
7   7       45  100-150  Kolkata        Bad  30000.0         1
8   8       34  200-250  Chennai  Excellent  10000.0         3
9   9       20  200-250  Kolkata       Good  60000.0         4

In [112]:
mydata.dtypes

ID            int64
age          object
fico         object
city         object
rating       object
balance     float64
children      int64
dtype: object

In [113]:
## Converting the age columns' datatype to int
mydata.age.value_counts()

15         8
30         8
20         7
10         7
45         6
34         5
12         4
7          3
missing    2
Name: age, dtype: int64

In [114]:
"""
errors = 'coerce' -->  The age col is object, we are trying to convert into integer.
But in the age col we have string values which has to be handled separately.
Hence we use  errors = 'coerce' , so that it will convert the string values to NaN.
"""

mydata['age'] = pd.to_numeric(mydata['age'], errors = 'coerce')

In [115]:
mydata.dtypes

ID            int64
age         float64
fico         object
city         object
rating       object
balance     float64
children      int64
dtype: object

In [116]:
mydata.age.value_counts()

15.0    8
30.0    8
20.0    7
10.0    7
45.0    6
34.0    5
12.0    4
7.0     3
Name: age, dtype: int64

In [117]:
mydata['age'].isnull().sum()

2

##### Filling NaN - Method 1

In [118]:
mydata[mydata['age'].isnull()].age

0    NaN
13   NaN
Name: age, dtype: float64

In [119]:
mydata['age'].fillna(mydata['age'].mean())

0     22.479167
1      7.000000
2     20.000000
3     20.000000
4     15.000000
5     20.000000
6     34.000000
7     45.000000
8     34.000000
9     20.000000
10    10.000000
11    15.000000
12    30.000000
13    22.479167
14    10.000000
15    45.000000
16     7.000000
17    10.000000
18    15.000000
19    20.000000
20    30.000000
21    30.000000
22    12.000000
23    12.000000
24    10.000000
25    15.000000
26    10.000000
27    30.000000
28     7.000000
29    15.000000
30    30.000000
31    20.000000
32    45.000000
33    30.000000
34    20.000000
35    45.000000
36    34.000000
37    45.000000
38    15.000000
39    10.000000
40    12.000000
41    15.000000
42    34.000000
43    12.000000
44    45.000000
45    30.000000
46    10.000000
47    30.000000
48    15.000000
49    34.000000
Name: age, dtype: float64

##### Filling NaN - Method 2

In [120]:
mydata['age'].isnull().sum()

2

In [121]:
mydata.loc[mydata['age'].isnull(), 'age'] = mydata['age'].mean()

mydata['age_children_ratio'] = mydata['age'] / mydata['children']

In [122]:
mydata

ID        age     fico     city     rating  balance  children  \
0    0  22.479167  100-150   Mumbai   Pathetic  50000.0         1   
1    1   7.000000  200-250  Chennai   Pathetic  30000.0         2   
2    2  20.000000  200-250  Chennai   Pathetic      NaN         3   
3    3  20.000000  200-250  Kolkata       Good  60000.0         3   
4    4  15.000000  100-150  Kolkata   Pathetic  30000.0         3   
5    5  20.000000  200-250  Chennai        Bad  60000.0         3   
6    6  34.000000  200-250    Delhi        Bad  60000.0         4   
7    7  45.000000  100-150  Kolkata        Bad  30000.0         1   
8    8  34.000000  200-250  Chennai  Excellent  10000.0         3   
9    9  20.000000  200-250  Kolkata       Good  60000.0         4   
10  10  10.000000  100-150    Delhi   Pathetic  50000.0         1   
11  11  15.000000  150-200   Mumbai  Excellent  10000.0         4   
12  12  30.000000  150-200  Kolkata       Good  60000.0         0   
13  13  22.479167  200-250    Delhi  Excellent  30000.0         1   
14  14  10.000000  200-250  Chennai   Pathetic  60000.0         0   
15  15  45.000000  250-300   Mumbai       Good  60000.0         4   
16  16   7.000000  250-300  Chennai       Good  50000.0         1   
17  17  10.000000  100-150   Mumbai  Excellent  10000.0         3   
18  18  15.000000  150-200  Chennai        Bad  40000.0         1   
19  19  20.000000  150-200  Kolkata   Pathetic  60000.0         4   
20  20  30.000000  200-250   Mumbai   Pathetic  60000.0         4   
21  21  30.000000  250-300    Delhi  Excellent  30000.0         2   
22  22  12.000000  200-250    Delhi  Excellent      NaN         2   
23  23  12.000000  150-200  Kolkata        Bad  30000.0         1   
24  24  10.000000  100-150  Chennai   Pathetic  60000.0         2   
25  25  15.000000  250-300    Delhi   Pathetic  10000.0         1   
26  26  10.000000  200-250  Chennai   Pathetic  40000.0         3   
27  27  30.000000  200-250    Delhi       Good  20000.0         1   
28  28   7.000000  100-150  Kolkata  Excellent  10000.0         3   
29  29  15.000000  200-250    Delhi   Pathetic  20000.0         0   
30  30  30.000000  200-250    Delhi   Pathetic      NaN         0   
31  31  20.000000  100-150  Kolkata  Excellent  50000.0         4   
32  32  45.000000  200-250   Mumbai  Excellent  50000.0         3   
33  33  30.000000  150-200  Kolkata       Good  50000.0         1   
34  34  20.000000  150-200  Chennai       Good  40000.0         3   
35  35  45.000000  200-250    Delhi        Bad  10000.0         1   
36  36  34.000000  100-150    Delhi        Bad  30000.0         0   
37  37  45.000000  250-300   Mumbai        Bad      NaN         2   
38  38  15.000000  150-200   Mumbai  Excellent  40000.0         0   
39  39  10.000000  200-250    Delhi  Excellent  60000.0         4   
40  40  12.000000  200-250    Delhi   Pathetic  30000.0         3   
41  41  15.000000  250-300   Mumbai   Pathetic  40000.0         2   
42  42  34.000000  250-300  Kolkata  Excellent  10000.0         4   
43  43  12.000000  250-300  Chennai        Bad      NaN         3   
44  44  45.000000  250-300    Delhi  Excellent  10000.0         4   
45  45  30.000000  250-300   Mumbai   Pathetic  10000.0         2   
46  46  10.000000  200-250  Kolkata        Bad  50000.0         1   
47  47  30.000000  250-300    Delhi       Good  40000.0         1   
48  48  15.000000  150-200    Delhi  Excellent  40000.0         2   
49  49  34.000000  100-150   Mumbai   Pathetic  50000.0         2   

    age_children_ratio  
0            22.479167  
1             3.500000  
2             6.666667  
3             6.666667  
4             5.000000  
5             6.666667  
6             8.500000  
7            45.000000  
8            11.333333  
9             5.000000  
10           10.000000  
11            3.750000  
12                 inf  
13           22.479167  
14                 inf  
15           11.250000  
16            7.000000  
17            3.333333  
18       

##### Adding columns

In [123]:
mydata['const_var'] = 100
mydata['balance_log'] = np.log(mydata['balance'])

In [124]:
mydata

ID        age     fico     city     rating  balance  children  \
0    0  22.479167  100-150   Mumbai   Pathetic  50000.0         1   
1    1   7.000000  200-250  Chennai   Pathetic  30000.0         2   
2    2  20.000000  200-250  Chennai   Pathetic      NaN         3   
3    3  20.000000  200-250  Kolkata       Good  60000.0         3   
4    4  15.000000  100-150  Kolkata   Pathetic  30000.0         3   
5    5  20.000000  200-250  Chennai        Bad  60000.0         3   
6    6  34.000000  200-250    Delhi        Bad  60000.0         4   
7    7  45.000000  100-150  Kolkata        Bad  30000.0         1   
8    8  34.000000  200-250  Chennai  Excellent  10000.0         3   
9    9  20.000000  200-250  Kolkata       Good  60000.0         4   
10  10  10.000000  100-150    Delhi   Pathetic  50000.0         1   
11  11  15.000000  150-200   Mumbai  Excellent  10000.0         4   
12  12  30.000000  150-200  Kolkata       Good  60000.0         0   
13  13  22.479167  200-250    Delhi  Excellent  30000.0         1   
14  14  10.000000  200-250  Chennai   Pathetic  60000.0         0   
15  15  45.000000  250-300   Mumbai       Good  60000.0         4   
16  16   7.000000  250-300  Chennai       Good  50000.0         1   
17  17  10.000000  100-150   Mumbai  Excellent  10000.0         3   
18  18  15.000000  150-200  Chennai        Bad  40000.0         1   
19  19  20.000000  150-200  Kolkata   Pathetic  60000.0         4   
20  20  30.000000  200-250   Mumbai   Pathetic  60000.0         4   
21  21  30.000000  250-300    Delhi  Excellent  30000.0         2   
22  22  12.000000  200-250    Delhi  Excellent      NaN         2   
23  23  12.000000  150-200  Kolkata        Bad  30000.0         1   
24  24  10.000000  100-150  Chennai   Pathetic  60000.0         2   
25  25  15.000000  250-300    Delhi   Pathetic  10000.0         1   
26  26  10.000000  200-250  Chennai   Pathetic  40000.0         3   
27  27  30.000000  200-250    Delhi       Good  20000.0         1   
28  28   7.000000  100-150  Kolkata  Excellent  10000.0         3   
29  29  15.000000  200-250    Delhi   Pathetic  20000.0         0   
30  30  30.000000  200-250    Delhi   Pathetic      NaN         0   
31  31  20.000000  100-150  Kolkata  Excellent  50000.0         4   
32  32  45.000000  200-250   Mumbai  Excellent  50000.0         3   
33  33  30.000000  150-200  Kolkata       Good  50000.0         1   
34  34  20.000000  150-200  Chennai       Good  40000.0         3   
35  35  45.000000  200-250    Delhi        Bad  10000.0         1   
36  36  34.000000  100-150    Delhi        Bad  30000.0         0   
37  37  45.000000  250-300   Mumbai        Bad      NaN         2   
38  38  15.000000  150-200   Mumbai  Excellent  40000.0         0   
39  39  10.000000  200-250    Delhi  Excellent  60000.0         4   
40  40  12.000000  200-250    Delhi   Pathetic  30000.0         3   
41  41  15.000000  250-300   Mumbai   Pathetic  40000.0         2   
42  42  34.000000  250-300  Kolkata  Excellent  10000.0         4   
43  43  12.000000  250-300  Chennai        Bad      NaN         3   
44  44  45.000000  250-300    Delhi  Excellent  10000.0         4   
45  45  30.000000  250-300   Mumbai   Pathetic  10000.0         2   
46  46  10.000000  200-250  Kolkata        Bad  50000.0         1   
47  47  30.000000  250-300    Delhi       Good  40000.0         1   
48  48  15.000000  150-200    Delhi  Excellent  40000.0         2   
49  49  34.000000  100-150   Mumbai   Pathetic  50000.0         2   

    age_children_ratio  const_var  balance_log  
0            22.479167        100    10.819778  
1             3.500000        100    10.308953  
2             6.666667        100          NaN  
3             6.666667        100    11.002100  
4             5.000000        100    10.308953  
5             6.666667        100    11.002100  
6             8.500000        100    11.002100  
7            45.000000        100    10.308953  
8            11.333333        100     9.210

In [125]:
## Converting the categorical value of Rating col into numeric
mydata['rating'].isnull().sum()

0

In [126]:
mydata['rating'].value_counts()

Pathetic     17
Excellent    14
Bad          10
Good          9
Name: rating, dtype: int64

In [127]:
mydata['rating_score'] = np.where(mydata['rating'].isin(['Good', 'Excellent']), 1, 0)

In [128]:
mydata['rating_score'].value_counts()

0    27
1    23
Name: rating_score, dtype: int64

In [129]:
mydata.loc[mydata['rating'] == 'Pathetic', 'rating_score'] = -1

In [130]:
mydata['rating_score'].value_counts()

 1    23
-1    17
 0    10
Name: rating_score, dtype: int64

In [131]:
mydata.head(10)

ID        age     fico     city     rating  balance  children  \
0   0  22.479167  100-150   Mumbai   Pathetic  50000.0         1   
1   1   7.000000  200-250  Chennai   Pathetic  30000.0         2   
2   2  20.000000  200-250  Chennai   Pathetic      NaN         3   
3   3  20.000000  200-250  Kolkata       Good  60000.0         3   
4   4  15.000000  100-150  Kolkata   Pathetic  30000.0         3   
5   5  20.000000  200-250  Chennai        Bad  60000.0         3   
6   6  34.000000  200-250    Delhi        Bad  60000.0         4   
7   7  45.000000  100-150  Kolkata        Bad  30000.0         1   
8   8  34.000000  200-250  Chennai  Excellent  10000.0         3   
9   9  20.000000  200-250  Kolkata       Good  60000.0         4   

   age_children_ratio  const_var  balance_log  rating_score  
0           22.479167        100    10.819778            -1  
1            3.500000        100    10.308953            -1  
2            6.666667        100          NaN            -1  
3            6.666667        100    11.002100             1  
4            5.000000        100    10.308953            -1  
5            6.666667        100    11.002100             0  
6            8.500000        100    11.002100             0  
7           45.000000        100    10.308953             0  
8           11.333333        100     9.210340             1  
9            5.000000        100    11.002100             1

In [132]:
## Splitting the col fico.

mydata.fico.value_counts()

200-250    20
250-300    11
100-150    10
150-200     9
Name: fico, dtype: int64

In [133]:
mydata.fico.isnull().sum()

0

In [134]:
mydata['fico'].str.split('-')

0     [100, 150]
1     [200, 250]
2     [200, 250]
3     [200, 250]
4     [100, 150]
5     [200, 250]
6     [200, 250]
7     [100, 150]
8     [200, 250]
9     [200, 250]
10    [100, 150]
11    [150, 200]
12    [150, 200]
13    [200, 250]
14    [200, 250]
15    [250, 300]
16    [250, 300]
17    [100, 150]
18    [150, 200]
19    [150, 200]
20    [200, 250]
21    [250, 300]
22    [200, 250]
23    [150, 200]
24    [100, 150]
25    [250, 300]
26    [200, 250]
27    [200, 250]
28    [100, 150]
29    [200, 250]
30    [200, 250]
31    [100, 150]
32    [200, 250]
33    [150, 200]
34    [150, 200]
35    [200, 250]
36    [100, 150]
37    [250, 300]
38    [150, 200]
39    [200, 250]
40    [200, 250]
41    [250, 300]
42    [250, 300]
43    [250, 300]
44    [250, 300]
45    [250, 300]
46    [200, 250]
47    [250, 300]
48    [150, 200]
49    [100, 150]
Name: fico, dtype: object

In [135]:
mydata['fico'].str.split('-', expand = True)

0    1
0   100  150
1   200  250
2   200  250
3   200  250
4   100  150
5   200  250
6   200  250
7   100  150
8   200  250
9   200  250
10  100  150
11  150  200
12  150  200
13  200  250
14  200  250
15  250  300
16  250  300
17  100  150
18  150  200
19  150  200
20  200  250
21  250  300
22  200  250
23  150  200
24  100  150
25  250  300
26  200  250
27  200  250
28  100  150
29  200  250
30  200  250
31  100  150
32  200  250
33  150  200
34  150  200
35  200  250
36  100  150
37  250  300
38  150  200
39  200  250
40  200  250
41  250  300
42  250  300
43  250  300
44  250  300
45  250  300
46  200  250
47  250  300
48  150  200
49  100  150

In [136]:
fico_values = mydata['fico'].str.split('-', expand = True).astype(float)

In [137]:
fico_values.head(10)

0      1
0  100.0  150.0
1  200.0  250.0
2  200.0  250.0
3  200.0  250.0
4  100.0  150.0
5  200.0  250.0
6  200.0  250.0
7  100.0  150.0
8  200.0  250.0
9  200.0  250.0

In [142]:
mydata['fico_min'] = fico_values[0]
mydata['fico_max'] = fico_values[1]

In [139]:
mydata.head(5)

ID        age     fico     city    rating  balance  children  \
0   0  22.479167  100-150   Mumbai  Pathetic  50000.0         1   
1   1   7.000000  200-250  Chennai  Pathetic  30000.0         2   
2   2  20.000000  200-250  Chennai  Pathetic      NaN         3   
3   3  20.000000  200-250  Kolkata      Good  60000.0         3   
4   4  15.000000  100-150  Kolkata  Pathetic  30000.0         3   

   age_children_ratio  const_var  balance_log  rating_score  fico_min  \
0           22.479167        100    10.819778            -1     100.0   
1            3.500000        100    10.308953            -1     200.0   
2            6.666667        100          NaN            -1     200.0   
3            6.666667        100    11.002100             1     200.0   
4            5.000000        100    10.308953            -1     100.0   

   fico_max  
0     150.0  
1     250.0  
2     250.0  
3     250.0  
4     150.0

In [140]:
del mydata['fico']

In [141]:
mydata.head(5)

ID        age     city    rating  balance  children  age_children_ratio  \
0   0  22.479167   Mumbai  Pathetic  50000.0         1           22.479167   
1   1   7.000000  Chennai  Pathetic  30000.0         2            3.500000   
2   2  20.000000  Chennai  Pathetic      NaN         3            6.666667   
3   3  20.000000  Kolkata      Good  60000.0         3            6.666667   
4   4  15.000000  Kolkata  Pathetic  30000.0         3            5.000000   

   const_var  balance_log  rating_score  fico_min  fico_max  
0        100    10.819778            -1     100.0     150.0  
1        100    10.308953            -1     200.0     250.0  
2        100          NaN            -1     200.0     250.0  
3        100    11.002100             1     200.0     250.0  
4        100    10.308953            -1     100.0     150.0

In [143]:
# Changing the categorical values of city and rating

In [144]:
mydata.city.value_counts()

Delhi      16
Kolkata    12
Mumbai     11
Chennai    11
Name: city, dtype: int64

In [145]:
mydata.city.isnull().sum()

0

In [150]:
mydata['mumbai_city'] = np.where(mydata['city'].isin(['Mumbai']), 1, 0)

In [162]:
mydata['delhi_city'] = np.where(mydata['city'].isin(['Delhi']),1, 0)

KeyError: 'city'

In [152]:
mydata['Kolkata_city'] = np.where(mydata['city'].isin(['Kolkata']), 1, 0)

In [156]:
mydata['Chennai_city'] = np.where(mydata['city'].isin(['Chennai']), 1, 0)

In [157]:
mydata.head(5)

ID        age     city    rating  balance  children  age_children_ratio  \
0   0  22.479167   Mumbai  Pathetic  50000.0         1           22.479167   
1   1   7.000000  Chennai  Pathetic  30000.0         2            3.500000   
2   2  20.000000  Chennai  Pathetic      NaN         3            6.666667   
3   3  20.000000  Kolkata      Good  60000.0         3            6.666667   
4   4  15.000000  Kolkata  Pathetic  30000.0         3            5.000000   

   const_var  balance_log  rating_score  fico_min  fico_max  mumbai_city  \
0        100    10.819778            -1     100.0     150.0            1   
1        100    10.308953            -1     200.0     250.0            0   
2        100          NaN            -1     200.0     250.0            0   
3        100    11.002100             1     200.0     250.0            0   
4        100    10.308953            -1     100.0     150.0            0   

   delhi_city  Kolkata_city  Chennai  Chennai_city  
0           0             0        0             0  
1           0             0        1             1  
2           0             0        1             1  
3           0             1        0             0  
4           0             1        0             0

In [160]:
del mydata['city']

In [163]:
mydata.head(6)

ID        age    rating  balance  children  age_children_ratio  const_var  \
0   0  22.479167  Pathetic  50000.0         1           22.479167        100   
1   1   7.000000  Pathetic  30000.0         2            3.500000        100   
2   2  20.000000  Pathetic      NaN         3            6.666667        100   
3   3  20.000000      Good  60000.0         3            6.666667        100   
4   4  15.000000  Pathetic  30000.0         3            5.000000        100   
5   5  20.000000       Bad  60000.0         3            6.666667        100   

   balance_log  rating_score  fico_min  fico_max  mumbai_city  delhi_city  \
0    10.819778            -1     100.0     150.0            1           0   
1    10.308953            -1     200.0     250.0            0           0   
2          NaN            -1     200.0     250.0            0           0   
3    11.002100             1     200.0     250.0            0           0   
4    10.308953            -1     100.0     150.0            0           0   
5    11.002100             0     200.0     250.0            0           0   

   Kolkata_city  Chennai_city  
0             0             0  
1             0             1  
2             0             1  
3             1             0  
4             1             0  
5             0             1

In [165]:
## For rating columns

dummy = pd.get_dummies(mydata['rating'], drop_first = True, prefix = 'rating')

In [166]:
dummy

rating_Excellent  rating_Good  rating_Pathetic
0                  0            0                1
1                  0            0                1
2                  0            0                1
3                  0            1                0
4                  0            0                1
5                  0            0                0
6                  0            0                0
7                  0            0                0
8                  1            0                0
9                  0            1                0
10                 0            0                1
11                 1            0                0
12                 0            1                0
13                 1            0                0
14                 0            0                1
15                 0            1                0
16                 0            1                0
17                 1            0                0
18                 0            0                0
19                 0            0                1
20                 0            0                1
21                 1            0                0
22                 1            0                0
23                 0            0                0
24                 0            0                1
25                 0            0                1
26                 0            0                1
27                 0            1                0
28                 1            0                0
29                 0            0                1
30                 0            0                1
31                 1            0                0
32                 1            0                0
33                 0            1                0
34                 0            1                0
35                 0            0                0
36                 0            0                0
37                 0            0                0
38                 1            0                0
39                 1            0                0
40                 0            0                1
41                 0            0                1
42                 1            0                0
43                 0            0                0
44                 1            0                0
45                 0            0                1
46                 0            0                0
47                 0            1                0
48                 1            0                0
49                 0            0                1

In [167]:
mydata = pd.concat(
    [mydata, dummy], axis = 1
)

In [168]:
del mydata['rating']

In [169]:
mydata

ID        age  balance  children  age_children_ratio  const_var  \
0    0  22.479167  50000.0         1           22.479167        100   
1    1   7.000000  30000.0         2            3.500000        100   
2    2  20.000000      NaN         3            6.666667        100   
3    3  20.000000  60000.0         3            6.666667        100   
4    4  15.000000  30000.0         3            5.000000        100   
5    5  20.000000  60000.0         3            6.666667        100   
6    6  34.000000  60000.0         4            8.500000        100   
7    7  45.000000  30000.0         1           45.000000        100   
8    8  34.000000  10000.0         3           11.333333        100   
9    9  20.000000  60000.0         4            5.000000        100   
10  10  10.000000  50000.0         1           10.000000        100   
11  11  15.000000  10000.0         4            3.750000        100   
12  12  30.000000  60000.0         0                 inf        100   
13  13  22.479167  30000.0         1           22.479167        100   
14  14  10.000000  60000.0         0                 inf        100   
15  15  45.000000  60000.0         4           11.250000        100   
16  16   7.000000  50000.0         1            7.000000        100   
17  17  10.000000  10000.0         3            3.333333        100   
18  18  15.000000  40000.0         1           15.000000        100   
19  19  20.000000  60000.0         4            5.000000        100   
20  20  30.000000  60000.0         4            7.500000        100   
21  21  30.000000  30000.0         2           15.000000        100   
22  22  12.000000      NaN         2            6.000000        100   
23  23  12.000000  30000.0         1           12.000000        100   
24  24  10.000000  60000.0         2            5.000000        100   
25  25  15.000000  10000.0         1           15.000000        100   
26  26  10.000000  40000.0         3            3.333333        100   
27  27  30.000000  20000.0         1           30.000000        100   
28  28   7.000000  10000.0         3            2.333333        100   
29  29  15.000000  20000.0         0                 inf        100   
30  30  30.000000      NaN         0                 inf        100   
31  31  20.000000  50000.0         4            5.000000        100   
32  32  45.000000  50000.0         3           15.000000        100   
33  33  30.000000  50000.0         1           30.000000        100   
34  34  20.000000  40000.0         3            6.666667        100   
35  35  45.000000  10000.0         1           45.000000        100   
36  36  34.000000  30000.0         0                 inf        100   
37  37  45.000000      NaN         2           22.500000        100   
38  38  15.000000  40000.0         0                 inf        100   
39  39  10.000000  60000.0         4            2.500000        100   
40  40  12.000000  30000.0         3            4.000000        100   
41  41  15.000000  40000.0         2            7.500000        100   
42  42  34.000000  10000.0         4            8.500000        100   
43  43  12.000000      NaN         3            4.000000        100   
44  44  45.000000  10000.0         4           11.250000        100   
45  45  30.000000  10000.0         2           15.000000        100   
46  46  10.000000  50000.0         1           10.000000        100   
47  47  30.000000  40000.0         1           30.000000        100   
48  48  15.000000  40000.0         2            7.500000        100   
49  49  34.000000  50000.0         2           17.000000        100   

    balance_log  rating_score  fico_min  fico_max  mumbai_city  delhi_city  \
0     10.819778            -1     100.0     150.0            1           0   
1     10.308953            -1     200.0     250.0            0           0   
2           NaN            -1     200.0     250.0            0           0   
3     11.002100             1     200.0     250.0            0        